[package]
name = "protocol-rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "protocol_rust"
path = "src/lib.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
